version: '3'

services: 
  app:
    build: ./app
    expose:
      - 5000
    ports:
      - 5000:5000
    volumes:
      - ./app:/usr/src/app
    env_file: 
      - ./app/.flaskenv
  frontend:
    build: ./frontend
    expose:
      - 3000
    environment: 
      - CI=true
    ports: 
      - 3000:3000
    volumes: 
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
    depends_on: 
      - app
  db:
    image: mysql:latest
    volumes: 
    - db_data:/var/lib/mysql
    restart: always
    environment: 
      MYSQL_DATABASE: CSE312DB
      MYSQL_USER: root
      MYSQL_PASSWORD: THISpain123
      MYSQL_ROOT_PASSWORD: eThah1ruW8ahgaigoom5quiesa9ahv2e
    expose: 
    - 3306
    ports: 
    - 3306:3306
volumes: 
  db_data: