version: '3'

services: 
  app:
    build: ./app
    expose:
      - 5000
    ports:
      - 5000:5000
    volumes:
      - ./app:/usr/src/app
    env_file: 
      - ./app/.flaskenv
    links:
      - db
  frontend:
    build: ./frontend
    expose:
      - 3000
    environment: 
      - CI=true
    ports: 
      - 3000:3000
    volumes: 
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
    depends_on: 
      - app
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
volumes: 
  mongodb_data_container: