version: '3'

services:
  backend:
    build: backend
    volumes:
      - ./backend:/backend
    environment: 
      - FLASK_APP=app.py
      - FLASK_ENV=development
    expose:
      - '5000'
    ports:
      - '5000:5000'

  reactfrontend:
    build: reactfrontend
    volumes:
      - ./reactfrontend:/reactfrontend
      - node-modules:/reactfrontend/node_modules
    environment:
      - NODE_ENV=development
    expose:
      - '3000'
    ports:
      - '3000:3000'
    depends_on:
      - backend
volumes:
  node-modules: